### ISSUE TITLE
error running mailer - no such file directory

### ISSUE THREAD

**Issue by mkadali99** [cloud-custodian/cloud-custodian#3132]
New to cloud-custodian and trying to get a hang of it. When I run the command, "c7n-mailer --config mailer.yml --update-lambda && custodian run -c test-policy.yml -s ", it created a lambda function. But there are errors in the log output window
Error starting mailer MailerSqsQueueProcessor(). 
 Error: [Errno 2] No such file or directory 
And also, in the code-inline editor, there was a warning message
The deployment package of your Lambda function "cloud-custodian-mailer" is too large to enable inline code editing. However, you can still invoke your function.

**Comment by chizou** [comment]
Are there any updates on this issue? I'm seeing a similar error.

If it's of any relevance, I tried adding `botocore` as one of the dependencies and when I add that to the deployment package, I'm getting the following new but similar error:
```
[ERROR] 2019-08-08T04:56:58.46Z 36fe265e-2659-4a2c-92bb-6de1a649f73f Error starting mailer MailerSqsQueueProcessor().
Error: SSL validation failed for https://queue.amazonaws.com/ [Errno 2] No such file or directory

Traceback (most recent call last):
File "/var/task/c7n_mailer/handle.py", line 46, in start_c7n_mailer
mailer_sqs_queue_processor.run(parallel)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 117, in run
for sqs_message in sqs_messages:
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 59, in __next__
AttributeNames=['SentTimestamp']
File "/var/task/botocore/client.py", line 357, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/task/botocore/client.py", line 648, in _make_api_call
operation_model, request_dict, request_context)
File "/var/task/botocore/client.py", line 667, in _make_request
return self._endpoint.make_request(operation_model, request_dict)
File "/var/task/botocore/endpoint.py", line 102, in make_request
return self._send_request(request_dict, operation_model)
File "/var/task/botocore/endpoint.py", line 137, in _send_request
success_response, exception):
File "/var/task/botocore/endpoint.py", line 231, in _needs_retry
caught_exception=caught_exception, request_dict=request_dict)
File "/var/task/botocore/hooks.py", line 356, in emit
return self._emitter.emit(aliased_event_name, **kwargs)
File "/var/task/botocore/hooks.py", line 228, in emit
return self._emit(event_name, kwargs)
File "/var/task/botocore/hooks.py", line 211, in _emit
response = handler(**kwargs)
File "/var/task/botocore/retryhandler.py", line 183, in __call__
if self._checker(attempts, response, caught_exception):
File "/var/task/botocore/retryhandler.py", line 251, in __call__
caught_exception)
File "/var/task/botocore/retryhandler.py", line 277, in _should_retry
return self._checker(attempt_number, response, caught_exception)
File "/var/task/botocore/retryhandler.py", line 317, in __call__
caught_exception)
File "/var/task/botocore/retryhandler.py", line 223, in __call__
attempt_number, caught_exception)
File "/var/task/botocore/retryhandler.py", line 359, in _check_caught_exception
raise caught_exception
SSLError: SSL validation failed for https://queue.amazonaws.com/ [Errno 2] No such file or directory
```

**Comment by chizou** [comment]
This is fixed once I upgraded the `certifi` module. Can `certifi` be added in the `requirements.txt`? Is there a valid reason for keeping an older version of it?

**Comment by taha23hasnain** [comment]
@kapilt facing this issue with a recent deploy of the mailer. Is there a solution for it?

**Comment by alanivey** [comment]
We experienced this too and found the following differences in the bundled packages uploaded to Lambda from a deployment in February that worked vs one in April that did not work:

```diff
$ diff -wu \
    <(cd cloud-custodian-mailer-8e52d6c1-9387-4338-8a49-002775707b25 && grep -Er '__version__\s+=' *) \
    <(cd cloud-custodian-mailer-f601a46e-a42d-48b9-81e4-c13ccd529080 && grep -Er '__version__\s+=' *)
--- /dev/fd/63	2022-05-02 16:02:31.000000000 -0400
+++ /dev/fd/62	2022-05-02 16:02:31.000000000 -0400
@@ -1,27 +1,29 @@
 certifi/__init__.py:__version__ = "2021.10.08"
-charset_normalizer/version.py:__version__ = "2.0.7"
+charset_normalizer/version.py:__version__ = "2.0.12"
 datadog/__init__.py:__version__ = get_version()
-decorator.py:__version__ = '5.1.0'
+decorator.py:__version__ = '5.1.1'
 idna/package_data.py:__version__ = '3.3'
 idna/idnadata.py:__version__ = '14.0.0'
 idna/uts46data.py:__version__ = '14.0.0'
-jinja2/__init__.py:__version__ = "3.0.2"
+jinja2/__init__.py:__version__ = "3.1.1"
 jmespath/__init__.py:__version__ = '0.10.0'
 jsonpatch.py:__version__ = '1.32'
-jsonpointer.py:__version__ = '2.2'
+jsonpointer.py:__version__ = '2.3'
 ldap3/version.py:__version__ = '2.9.1'
-markupsafe/__init__.py:__version__ = "2.0.1"
+markupsafe/__init__.py:__version__ = "2.1.1"
-pkg_resources/_vendor/packaging/__about__.py:__version__ = "16.8"
+pkg_resources/_vendor/packaging/__about__.py:__version__ = "21.3"
+pkg_resources/_vendor/more_itertools/__init__.py:__version__ = '8.12.0'
 pkg_resources/_vendor/appdirs.py:__version__ = '.'.join(map(str, __version_info__))
 pkg_resources/_vendor/six.py:__version__ = "1.10.0"
-pkg_resources/_vendor/pyparsing.py:__version__ = "2.1.10"
+pkg_resources/_vendor/pyparsing.py:__version__ = "2.2.1"
 pyasn1/__init__.py:__version__ = '0.4.8'
 python_http_client/__init__.py:        __version__ = version_file.read().strip()
-redis/__init__.py:__version__ = '3.5.3'
+redis/__init__.py:    __version__ = metadata.version("redis")
+redis/__init__.py:    __version__ = "99.99.99"
-requests/__version__.py:__version__ = '2.26.0'
+requests/__version__.py:__version__ = '2.27.1'
-sendgrid/version.py:__version__ = '6.9.5'
+sendgrid/version.py:__version__ = '6.9.7'
-urllib3/_version.py:__version__ = "1.26.7"
+urllib3/_version.py:__version__ = "1.26.9"
 urllib3/__init__.py:__version__ = __version__
 urllib3/packages/six.py:__version__ = "1.16.0"
-urllib3/packages/ssl_match_hostname/_implementation.py:__version__ = "3.5.0.1"
+urllib3/util/ssl_match_hostname.py:__version__ = "3.5.0.1"
-yaml/__init__.py:__version__ = '5.4.1'
+yaml/__init__.py:__version__ = '6.0
```

**Comment by jainnishant** [comment]
@kapilt - Still getting the issue with the c7n-mailer aws lambda with the latest version - 

Error starting mailer MailerSqsQueueProcessor(). 
 Error: SSL validation failed for https://sqs.eu-west-2.amazonaws.com/ [Errno 2] No such file or directory 

Traceback (most recent call last):
  File "/var/task/urllib3/util/ssl_.py", line 402, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/runtime/botocore/httpsession.py", line 455, in send
    urllib_response = conn.urlopen(
  File "/var/task/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/var/task/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/var/task/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/var/task/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/var/task/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/var/task/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/var/task/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/var/task/urllib3/util/ssl_.py", line 404, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/c7n_mailer/handle.py", line 33, in start_c7n_mailer
    mailer_sqs_queue_processor.run(parallel)
  File "/var/task/c7n_mailer/sqs_queue_processor.py", line 100, in run
    for sqs_message in sqs_messages:
  File "/var/task/c7n_mailer/sqs_queue_processor.py", line 37, in __next__
    response = self.aws_sqs.receive_message(
  File "/var/runtime/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 943, in _make_api_call
    http, parsed_response = self._make_request(
  File "/var/runtime/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/var/runtime/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/var/runtime/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/var/runtime/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/var/runtime/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/var/runtime/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/var/runtime/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/var/runtime/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/var/runtime/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/var/runtime/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/var/runtime/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/var/runtime/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/var/runtime/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/var/runtime/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/var/runtime/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/var/runtime/botocore/httpsession.py", line 482, in send
    raise SSLError(endpoint_url=request.url, error=e)
botocore.exceptions.SSLError: SSL validation failed for https://sqs.eu-west-2.amazonaws.com/ [Errno 2] No such file or directory
